# WSDL to Java code generation
quarkus.cxf.codegen.wsdl2java.includes=wsdl/*.wsdl
# quarkus.cxf.codegen.wsdl2java.additional-params = -impl
# Proxy settings (only needed if behind reverse proxy)
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.enable-forwarded-prefix=true
# Container build
quarkus.container-image.builder=jib
quarkus.container-image.build=true
quarkus.container-image.push=false
quarkus.container-image.group=service-health.de/uhp
quarkus.container-image.name=popp-smartphone-konnektor
quarkus.container-image.tag=latest
# Quarkus config
quarkus.http.host=0.0.0.0
quarkus.log.level=INFO
quarkus.otel.metrics.enabled
popp.real-connector-url=${POPP_REAL_CONNECTOR_URL:https://192.168.178.42}
popp.smartphone-connector-url=${POPP_SMARTPHONE_CONNECTOR_URL:https://localhost:9443}
popp.smcb-handle=${POPP_SMCB_HANDLE:SMC-B-10}
popp.client-url=${POPP_CLIENT_URL:http://localhost:8081}
quarkus.ssl.native=true
quarkus.http.ssl-port=9443
quarkus.http.port=8780
quarkus.http.ssl.client-auth=request
quarkus.http.ssl.certificate.key-store-file=META-INF/resources/server.keystore
quarkus.http.ssl.certificate.key-store-password=password
konnektor-proxy.keystore-path=${POPP_REAL_CONNECTOR_KEYSTORE_PATH}
konnektor-proxy.keystore-password=${POPP_REAL_CONNECTOR_KEYSTORE_PASSWORD}
konnektor-proxy.trust-all-hosts=${POPP_REAL_CONNECTOR_TRUST_ALL}
