/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package de.gematik.ws.conn.eventservice.wsdl.v7_2;

import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.logging.Logger;

import de.gematik.ws.conn.connectorcommon.v5.Status;
import de.gematik.ws.conn.eventservice.v7.GetCardsResponse;
import de.gematik.ws.conn.eventservice.v7.GetSubscriptionResponse;
import de.gematik.ws.conn.eventservice.v7.SubscribeResponse;
import de.gematik.ws.conn.eventservice.v7.SubscriptionType;
import de.gematik.ws.conn.eventservice.v7.UnsubscribeResponse;
import de.servicehealth.popp.session.Entry;
import de.servicehealth.popp.session.Store;
import io.quarkus.logging.Log;
import io.quarkus.security.identity.SecurityIdentity;
import jakarta.inject.Inject;

/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-20T23:45:08.791+01:00
 * Generated source version: 4.1.4
 *
 */

@jakarta.jws.WebService(
                      serviceName = "EventService",
                      portName = "EventServicePort",
                      targetNamespace = "http://ws.gematik.de/conn/EventService/WSDL/v7.2",
                      wsdlLocation = "classpath:/wsdl/EventService.wsdl",
                      endpointInterface = "de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType")

public class EventServicePortImpl implements EventServicePortType {

    @Inject
    SecurityIdentity identity; // Inject the SecurityIdentity

    @Inject
    Store store;

    @Inject
    Subscriptions subscriptions;


    private static final Logger LOG = Logger.getLogger(EventServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#subscribe(de.gematik.ws.conn.eventservice.v7.Subscribe parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.SubscribeResponse subscribe(de.gematik.ws.conn.eventservice.v7.Subscribe parameter) throws FaultMessage   {
        
        try {
            LOG.info("Executing operation subscribe");
            
            List<SubscriptionType> subscriptions = getSubscriptions();
            if(!subscriptions.stream().anyMatch(sub -> 
                (sub.getEventTo() == null || sub.getEventTo().equals(parameter.getSubscription().getEventTo())) &&
                (sub.getTopic() == null || sub.getTopic().equals(parameter.getSubscription().getTopic())) &&
                (sub.getFilter() == null || sub.getFilter().equals(parameter.getSubscription().getFilter()))
            )) {
                Log.warn("subscription does already exist. Not added.");
                parameter.getSubscription().setSubscriptionID(UUID.randomUUID().toString());
                subscriptions.add(parameter.getSubscription());
            }
            de.gematik.ws.conn.eventservice.v7.SubscribeResponse _return = new SubscribeResponse();
            _return.setStatus(new Status());
            _return.getStatus().setResult("OK");
            _return.setSubscriptionID(parameter.getSubscription().getSubscriptionID());
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new FaultMessage("FaultMessage...", ex);
        }
    }

    private List<SubscriptionType> getSubscriptions() {
        String tlsCertCN = getTlsCertCN();
        LOG.fine("Authenticated user: " + identity.getPrincipal().getName());
   
        List<SubscriptionType> subscriptionTypes = subscriptions.getTlsCertCN2subscriptions().get(tlsCertCN);
        if (subscriptionTypes == null) {
            subscriptionTypes = new CopyOnWriteArrayList<>();
            subscriptions.getTlsCertCN2subscriptions().put(tlsCertCN, subscriptionTypes);
        }
        return subscriptionTypes;
    }

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#getResourceInformation(de.gematik.ws.conn.eventservice.v7.GetResourceInformation parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.GetResourceInformationResponse getResourceInformation(de.gematik.ws.conn.eventservice.v7.GetResourceInformation parameter) throws FaultMessage   {
        LOG.info("Executing operation getResourceInformation");
        System.out.println(parameter);
        LOG.fine("Authenticated user: " + identity.getPrincipal().getName());
        try {
            de.gematik.ws.conn.eventservice.v7.GetResourceInformationResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new FaultMessage("FaultMessage...", ex);
        }
        //throw new FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#getSubscription(de.gematik.ws.conn.eventservice.v7.GetSubscription parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.GetSubscriptionResponse getSubscription(de.gematik.ws.conn.eventservice.v7.GetSubscription parameter) throws FaultMessage   {
        LOG.info("Executing operation getSubscription");
        try {
            de.gematik.ws.conn.eventservice.v7.GetSubscriptionResponse _return = new GetSubscriptionResponse();
            Optional<SubscriptionType> subscription = getSubscriptions().stream().filter(sub -> sub.getSubscriptionID().equals(parameter.getSubscriptionID())).findFirst();
            _return.setStatus(new Status());
            if(subscription.isPresent()) {
                _return.getSubscriptions().getSubscription().add(subscription.get());
                _return.getStatus().setResult("OK");
            } else {
                _return.getStatus().setResult("NOT_FOUND");
            }
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new FaultMessage("FaultMessage...", ex);
        }
        //throw new FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#unsubscribe(de.gematik.ws.conn.eventservice.v7.Unsubscribe parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.UnsubscribeResponse unsubscribe(de.gematik.ws.conn.eventservice.v7.Unsubscribe parameter) throws FaultMessage   {
        LOG.info("Executing operation unsubscribe");
        try {
            getSubscriptions().removeIf(sub -> sub.getSubscriptionID().equals(parameter.getSubscriptionID()));
            de.gematik.ws.conn.eventservice.v7.UnsubscribeResponse _return = new UnsubscribeResponse();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new FaultMessage("FaultMessage...", ex);
        }
        //throw new FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#getCardTerminals(de.gematik.ws.conn.eventservice.v7.GetCardTerminals parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.GetCardTerminalsResponse getCardTerminals(de.gematik.ws.conn.eventservice.v7.GetCardTerminals parameter) throws FaultMessage   {
        LOG.info("Executing operation getCardTerminals");
        System.out.println(parameter);
        try {
            de.gematik.ws.conn.eventservice.v7.GetCardTerminalsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#renewSubscriptions(de.gematik.ws.conn.eventservice.v7.RenewSubscriptions parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.RenewSubscriptionsResponse renewSubscriptions(de.gematik.ws.conn.eventservice.v7.RenewSubscriptions parameter) throws FaultMessage   {
        LOG.info("Executing operation renewSubscriptions");
        System.out.println(parameter);
        try {
            de.gematik.ws.conn.eventservice.v7.RenewSubscriptionsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#getCards(de.gematik.ws.conn.eventservice.v7.GetCards parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.GetCardsResponse getCards(de.gematik.ws.conn.eventservice.v7.GetCards parameter) throws FaultMessage   {
        LOG.info("Executing operation getCards");
        System.out.println(parameter);
        try {
            String tlsCertCN = getTlsCertCN();
            LOG.fine("Authenticated user: " + identity.getPrincipal().getName());

            
            de.gematik.ws.conn.eventservice.v7.GetCardsResponse _return = new GetCardsResponse();
            _return.setCards(new de.gematik.ws.conn.cardservice.v8.Cards());
            _return.setStatus(new de.gematik.ws.conn.connectorcommon.v5.Status());
            List<Entry> entries = store.getTlsCertCNs2cards().get(tlsCertCN);
            if(entries != null) {
                _return.getCards().getCard().addAll(entries.stream().map(entry -> entry.getCardInfoType()).toList());
            }
            _return.getStatus().setResult("OK");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("FaultMessage...");
    }

    private String getTlsCertCN() {
        String tlsCertCN = identity.getPrincipal().getName();
        if ("".equals(tlsCertCN) || tlsCertCN == null) {
            tlsCertCN = "null";
        }
        return tlsCertCN;
    }

}
