/** Please modify this class to meet your needs This class is not complete */
package de.gematik.ws.conn.eventservice.wsdl.v7_2;

import com.google.common.base.Strings;
import de.gematik.ws.conn.cardservice.v8.CardInfoType;
import de.gematik.ws.conn.cardservice.v8.Cards;
import de.gematik.ws.conn.cardservicecommon.v2.CardTypeType;
import de.gematik.ws.conn.connectorcommon.v5.Status;
import de.gematik.ws.conn.eventservice.v7.GetCardTerminals;
import de.gematik.ws.conn.eventservice.v7.GetCardTerminalsResponse;
import de.gematik.ws.conn.eventservice.v7.GetCards;
import de.gematik.ws.conn.eventservice.v7.GetCardsResponse;
import de.gematik.ws.conn.eventservice.v7.GetResourceInformation;
import de.gematik.ws.conn.eventservice.v7.GetResourceInformationResponse;
import de.gematik.ws.conn.eventservice.v7.GetSubscription;
import de.gematik.ws.conn.eventservice.v7.GetSubscriptionResponse;
import de.gematik.ws.conn.eventservice.v7.RenewSubscriptions;
import de.gematik.ws.conn.eventservice.v7.RenewSubscriptionsResponse;
import de.gematik.ws.conn.eventservice.v7.Subscribe;
import de.gematik.ws.conn.eventservice.v7.SubscribeResponse;
import de.gematik.ws.conn.eventservice.v7.SubscriptionRenewal;
import de.gematik.ws.conn.eventservice.v7.SubscriptionType;
import de.gematik.ws.conn.eventservice.v7.Unsubscribe;
import de.gematik.ws.conn.eventservice.v7.UnsubscribeResponse;
import de.servicehealth.event.EventServiceClient;
import de.servicehealth.popp.session.Store;
import de.servicehealth.popp.session.WebsocketEntry;
import io.quarkus.logging.Log;
import io.quarkus.security.identity.SecurityIdentity;
import jakarta.inject.Inject;
import jakarta.jws.WebService;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.logging.Logger;
import javax.naming.InvalidNameException;
import javax.naming.ldap.LdapName;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeConstants;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * This class was generated by Apache CXF 4.1.4 2026-01-20T23:45:08.791+01:00 Generated source
 * version: 4.1.4
 */
@WebService(
    serviceName = "EventService",
    portName = "EventServicePort",
    targetNamespace = "http://ws.gematik.de/conn/EventService/WSDL/v7.2",
    wsdlLocation = "classpath:/wsdl/EventService.wsdl",
    endpointInterface = "de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType")
public class EventServicePortImpl implements EventServicePortType {

  @Inject SecurityIdentity identity;

  @Inject Store store;

  @Inject Subscriptions subscriptions;

  @Inject EventServiceClient eventServiceClient;

  private static final Logger LOG = Logger.getLogger(EventServicePortImpl.class.getName());

  /* (non-Javadoc)
   * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#subscribe(de.gematik.ws.conn.eventservice.v7.Subscribe parameter)*
   */
  public SubscribeResponse subscribe(Subscribe parameter) throws FaultMessage {

    var tlsCertCn = getTlsCertCN();
    try {
      LOG.fine("Executing operation subscribe");
      var exisitingSubscription =
          subscriptions.findSubscription(
              getTlsCertCN(),
              sub ->
                  (sub.getEventTo() == null
                          || sub.getEventTo().equals(parameter.getSubscription().getEventTo()))
                      && (sub.getTopic() == null
                          || sub.getTopic().equals(parameter.getSubscription().getTopic()))
                      && (sub.getFilter() == null
                          || sub.getFilter().equals(parameter.getSubscription().getFilter())));
      if (exisitingSubscription.isEmpty()) {
        var newSubscriptionId = UUID.randomUUID().toString();

        Log.info("New subscription Adding with ID: " + newSubscriptionId);

        var parameterSubscription = parameter.getSubscription();
        // We have to set a termination time, even if none is passed. Otherwise some Primary Systems
        // will fail when retrieving the subscription
        if (parameterSubscription.getTerminationTime() == null) {
          XMLGregorianCalendar xmlCal = getTimeInOneHour();
          parameterSubscription.setTerminationTime(xmlCal);
        }
        parameter.getSubscription().setSubscriptionID(newSubscriptionId);
        parameter
            .getSubscription()
            .setTerminationTime(parameter.getSubscription().getTerminationTime());
        subscriptions.addSubscription(tlsCertCn, parameter.getSubscription());
      }
      SubscribeResponse _return = new SubscribeResponse();
      _return.setStatus(new Status());
      _return.getStatus().setResult("OK");
      _return.setSubscriptionID(parameter.getSubscription().getSubscriptionID());
      _return.setTerminationTime(parameter.getSubscription().getTerminationTime());
      return _return;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new FaultMessage("FaultMessage...", ex);
    }
  }

  private List<SubscriptionType> getSubscriptions() {
    String tlsCertCN = getTlsCertCN();

    List<SubscriptionType> subscriptionTypes = subscriptions.getSubscriptions(tlsCertCN);

    // purge terminated subscriptions
    try {
      XMLGregorianCalendar now =
          DatatypeFactory.newInstance()
              .newXMLGregorianCalendar(
                  GregorianCalendar.from(Instant.now().atZone(ZoneOffset.UTC)));

      subscriptions.removeSubscription(
          tlsCertCN,
          (subscription) ->
              subscription.getTerminationTime().compare(now) == DatatypeConstants.LESSER);

    } catch (DatatypeConfigurationException e) {
      throw new RuntimeException(e);
    }

    return subscriptionTypes;
  }

  /* (non-Javadoc)
   * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#getResourceInformation(de.gematik.ws.conn.eventservice.v7.GetResourceInformation parameter)*
   */
  public GetResourceInformationResponse getResourceInformation(GetResourceInformation parameter)
      throws FaultMessage {
    try {
      return null;
    } catch (Exception ex) {
      Log.error(ex.getMessage());
      throw new FaultMessage("FaultMessage...", ex);
    }
    // throw new FaultMessage("FaultMessage...");
  }

  /* (non-Javadoc)
   * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#getSubscription(de.gematik.ws.conn.eventservice.v7.GetSubscription parameter)*
   */
  public GetSubscriptionResponse getSubscription(GetSubscription parameter) throws FaultMessage {
    LOG.fine("Executing operation getSubscription");
    try {
      GetSubscriptionResponse _return = new GetSubscriptionResponse();

      List<SubscriptionType> subscription =
          getSubscriptions().stream()
              .filter(
                  sub -> {
                    if (Strings.isNullOrEmpty(parameter.getSubscriptionID())) {
                      return true;
                    } else {
                      return sub.getSubscriptionID().equals(parameter.getSubscriptionID());
                    }
                  })
              .toList();

      _return.setStatus(new Status());
      _return.getStatus().setResult("OK");
      _return.setSubscriptions(new GetSubscriptionResponse.Subscriptions());

      for (SubscriptionType subscriptionType : subscription) {
        _return.getSubscriptions().getSubscription().add(subscriptionType);
      }

      return _return;
    } catch (Exception ex) {
      ex.printStackTrace();
      throw new FaultMessage("FaultMessage...", ex);
    }
    // throw new FaultMessage("FaultMessage...");
  }

  /* (non-Javadoc)
   * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#unsubscribe(de.gematik.ws.conn.eventservice.v7.Unsubscribe parameter)*
   */
  public UnsubscribeResponse unsubscribe(Unsubscribe parameter) throws FaultMessage {
    LOG.fine("Executing operation unsubscribe");

    subscriptions.removeSubscription(
        getTlsCertCN(),
        subscriptionType ->
            subscriptionType.getSubscriptionID().equals(parameter.getSubscriptionID()));

    return new UnsubscribeResponse();
  }

  /* (non-Javadoc)
   * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#getCardTerminals(de.gematik.ws.conn.eventservice.v7.GetCardTerminals parameter)*
   */
  public GetCardTerminalsResponse getCardTerminals(GetCardTerminals parameter) throws FaultMessage {
    LOG.fine("Executing operation getCardTerminals");
    return null;
  }

  /* (non-Javadoc)
   * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#renewSubscriptions(de.gematik.ws.conn.eventservice.v7.RenewSubscriptions parameter)*
   */
  public RenewSubscriptionsResponse renewSubscriptions(RenewSubscriptions parameter)
      throws FaultMessage {
    LOG.fine("Executing operation renewSubscriptions");
    System.out.println(parameter);

    List<SubscriptionRenewal> renewals = new ArrayList<>();
    XMLGregorianCalendar inOneHour;

    try {
      inOneHour = getTimeInOneHour();
    } catch (DatatypeConfigurationException ex) {
      LOG.severe(ex.getMessage());
      throw new FaultMessage(ex.getMessage());
    }

    for (String id : parameter.getSubscriptionID()) {
      var subscription =
          getSubscriptions().stream()
              .filter(subscriptionType -> subscriptionType.getSubscriptionID().equals(id))
              .findFirst();

      if (subscription.isEmpty()) {
        continue;
      }

      subscription.get().setTerminationTime(inOneHour);

      var renewal = new SubscriptionRenewal();
      renewal.setSubscriptionID(id);
      renewal.setTerminationTime(inOneHour);
      renewals.add(renewal);
    }

    var response = new RenewSubscriptionsResponse();
    var subscribeRenewals = new RenewSubscriptionsResponse.SubscribeRenewals();
    var status = new Status();

    response.setSubscribeRenewals(subscribeRenewals);
    response.getSubscribeRenewals().getSubscriptionRenewal().addAll(renewals);
    status.setResult("OK");
    response.setStatus(status);

    return response;
  }

  /* (non-Javadoc)
   * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#getCards(de.gematik.ws.conn.eventservice.v7.GetCards parameter)*
   */
  public GetCardsResponse getCards(GetCards parameter) throws FaultMessage {
    LOG.info("Executing operation getCards. param: " + parameter.getCardType());
    var cardTypeParameter = Optional.ofNullable(parameter.getCardType());
    String tlsCertCN = getTlsCertCN();
    LOG.info("getting smcbs");
    CardInfoType smcbCardInfoType = getSmcb();
    LOG.info("done getting smcbs");
    LOG.info("Authenticated user: " + identity.getPrincipal().getName());

    GetCardsResponse _return = new GetCardsResponse();
    _return.setCards(new Cards());
    _return.setStatus(new Status());

    if (cardTypeParameter.map(card -> card == CardTypeType.EGK).orElse(true)) {
      List<WebsocketEntry> entries = store.getEntriesOfCertCN(tlsCertCN);
      _return
          .getCards()
          .getCard()
          .addAll(entries.stream().map(WebsocketEntry::getCardInfoType).toList());
    }

    if (cardTypeParameter.map(card -> card == CardTypeType.SMC_B).orElse(true)) {
      LOG.info("Returning smcb: " + smcbCardInfoType.getIccsn());
      // In order to make ere ps app happy we need to tell it that an smcb actually exists
      _return.getCards().getCard().add(smcbCardInfoType);
    }

    _return.getStatus().setResult("OK");
    return _return;
  }

  private String getTlsCertCN() {
    LdapName ldapName;
    try {
      ldapName = new LdapName(identity.getPrincipal().getName());
    } catch (InvalidNameException e) {
      throw new RuntimeException(e);
    }
    String cn =
        ldapName.getRdns().stream()
            .filter(rdn -> rdn.getType().equalsIgnoreCase("CN"))
            .map(rdn -> rdn.getValue().toString())
            .findFirst()
            .orElseThrow();
    return cn.isEmpty() ? null : cn.replace("CN=", "");
  }

  private CardInfoType getSmcb() throws FaultMessage {
    String certCn = getTlsCertCN();
    if (Objects.isNull(certCn)) {
      throw new FaultMessage("Could not find certCn");
    }

    return eventServiceClient.getCards().getCards().getCard().stream()
        .filter(card -> card.getIccsn().equals(certCn.substring(0, 20)))
        .findFirst()
        .orElseThrow(FaultMessage::new);
  }

  private XMLGregorianCalendar getTimeInOneHour() throws DatatypeConfigurationException {
    return DatatypeFactory.newInstance()
        .newXMLGregorianCalendar(
            GregorianCalendar.from(Instant.now().plus(1, ChronoUnit.HOURS).atZone(ZoneOffset.UTC)));
  }
}
