/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package de.gematik.ws.conn.eventservice.wsdl.v7_2;

import java.util.logging.Logger;

import de.gematik.ws.conn.eventservice.v7.GetCardsResponse;
import de.servicehealth.popp.session.Store;
import io.quarkus.security.identity.SecurityIdentity;
import jakarta.inject.Inject;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-20T23:45:08.791+01:00
 * Generated source version: 4.1.4
 *
 */

@jakarta.jws.WebService(
                      serviceName = "EventService",
                      portName = "EventServicePort",
                      targetNamespace = "http://ws.gematik.de/conn/EventService/WSDL/v7.2",
                      wsdlLocation = "classpath:/wsdl/EventService.wsdl",
                      endpointInterface = "de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType")

public class EventServicePortImpl implements EventServicePortType {

    @Inject
    SecurityIdentity identity; // Inject the SecurityIdentity

    @Inject
    Store store;

    private static final Logger LOG = Logger.getLogger(EventServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#subscribe(de.gematik.ws.conn.eventservice.v7.Subscribe parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.SubscribeResponse subscribe(de.gematik.ws.conn.eventservice.v7.Subscribe parameter) throws FaultMessage   {
        LOG.info("Executing operation subscribe");
        System.out.println(parameter);
        LOG.fine("Authenticated user: " + identity.getPrincipal().getName());
        try {
            de.gematik.ws.conn.eventservice.v7.SubscribeResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#getResourceInformation(de.gematik.ws.conn.eventservice.v7.GetResourceInformation parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.GetResourceInformationResponse getResourceInformation(de.gematik.ws.conn.eventservice.v7.GetResourceInformation parameter) throws FaultMessage   {
        LOG.info("Executing operation getResourceInformation");
        System.out.println(parameter);
        LOG.fine("Authenticated user: " + identity.getPrincipal().getName());
        try {
            de.gematik.ws.conn.eventservice.v7.GetResourceInformationResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#getSubscription(de.gematik.ws.conn.eventservice.v7.GetSubscription parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.GetSubscriptionResponse getSubscription(de.gematik.ws.conn.eventservice.v7.GetSubscription parameter) throws FaultMessage   {
        LOG.info("Executing operation getSubscription");
        System.out.println(parameter);
        try {
            de.gematik.ws.conn.eventservice.v7.GetSubscriptionResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#unsubscribe(de.gematik.ws.conn.eventservice.v7.Unsubscribe parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.UnsubscribeResponse unsubscribe(de.gematik.ws.conn.eventservice.v7.Unsubscribe parameter) throws FaultMessage   {
        LOG.info("Executing operation unsubscribe");
        System.out.println(parameter);
        try {
            de.gematik.ws.conn.eventservice.v7.UnsubscribeResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#getCardTerminals(de.gematik.ws.conn.eventservice.v7.GetCardTerminals parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.GetCardTerminalsResponse getCardTerminals(de.gematik.ws.conn.eventservice.v7.GetCardTerminals parameter) throws FaultMessage   {
        LOG.info("Executing operation getCardTerminals");
        System.out.println(parameter);
        try {
            de.gematik.ws.conn.eventservice.v7.GetCardTerminalsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#renewSubscriptions(de.gematik.ws.conn.eventservice.v7.RenewSubscriptions parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.RenewSubscriptionsResponse renewSubscriptions(de.gematik.ws.conn.eventservice.v7.RenewSubscriptions parameter) throws FaultMessage   {
        LOG.info("Executing operation renewSubscriptions");
        System.out.println(parameter);
        try {
            de.gematik.ws.conn.eventservice.v7.RenewSubscriptionsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see de.gematik.ws.conn.eventservice.wsdl.v7_2.EventServicePortType#getCards(de.gematik.ws.conn.eventservice.v7.GetCards parameter)*
     */
    public de.gematik.ws.conn.eventservice.v7.GetCardsResponse getCards(de.gematik.ws.conn.eventservice.v7.GetCards parameter) throws FaultMessage   {
        LOG.info("Executing operation getCards");
        System.out.println(parameter);
        try {
            String tlsCertCN = identity.getPrincipal().getName();
            LOG.fine("Authenticated user: " + identity.getPrincipal().getName());

            
            de.gematik.ws.conn.eventservice.v7.GetCardsResponse _return = new GetCardsResponse();
            _return.setCards(new de.gematik.ws.conn.cardservice.v8.Cards());
            _return.setStatus(new de.gematik.ws.conn.connectorcommon.v5.Status());
            _return.getCards().getCard().addAll(store.getTlsCertCNs2cards().get(tlsCertCN).stream().map(entry -> entry.getCardInfoType()).toList());
            _return.getStatus().setResult("OK");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("FaultMessage...");
    }

}
