@startuml
!theme plain

participant "eGK" as egk
participant "Smartphone" as phone
participant "smart-phone-popp-\nkonnektor-server" as connector
participant "ere-ps-app" as app
participant "popp-sample-code-\npopp-client" as client
participant "popp-service" as service
participant "E-Rezept\nFachdienst" as fachdienst

== Generate session & card inserted ==
phone -> phone: generate cardSessionId
phone -> connector: WebSocket connect
phone -> connector: 1 WebSocket TextFame: registerEGK\n(cardSessionId)
connector -> app: 2 CETP CARD_INSERTED\n(cardSessionId as card handle)

== readVSD ==
app -> connector: 3 SOAP readVSD\n(cardSessionId as card handle)
connector -> client: 4 HTTP GET contact-connector\n(cardSessionId)

== PoPP Authentifizierung ==
client -> service: Zeta Auth (Details not shown)
client -> service: WebSocket connect (Details not shown)
client -> service: start message\n(client session id)

== APDU Communication ==
service -> client: SignedScenario with StandardScenarioMessage including APDU steps
client -> connector: SecureSendAPDU\n(SignedScenario)
connector -> phone: SendAPDU\n(ScenarioSteps übersetzt)
phone -> egk: Open PACE channel
activate egk
phone -> egk: sendAPDU
egk --> phone: respond APDU
deactivate egk
phone -> connector: sendAPDUResponse
connector -> client: SecureSendAPDUResponse
client -> service: ScenarioResponseMessage

== PoPP-Token Exchange ==
service -> client: PoPP Token
client -> connector: PoPP Token
connector -> app: ReadVSD Antwort\n(PoPP Token in field Pruefnachweis)

== E-Rezepte abrufen ==
app -> fachdienst: get E-Rezepte\n(with PoPP-Token)
fachdienst --> app: FHIR Bundle E-Rezepte

== E-Rezepte an Smartphone ==
app -> connector: WebSocket Connect
app -> connector: ERezepteFromAVS\n(E-Rezepte)
connector -> phone: E-Rezepte

@enduml