package de.gematik.ws.conn.vsds.vsdservice.v5_2;

import java.net.URI;

import org.eclipse.microprofile.config.inject.ConfigProperty;

import de.gematik.ws.conn.vsds.vsdservice.v5.ReadVSD;
import de.gematik.ws.conn.vsds.vsdservice.v5.ReadVSDResponse;

/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-02-02T22:57:04.219+01:00
 * Generated source version: 4.1.4
 *
 */
@jakarta.jws.WebService(
                      serviceName = "VSDService",
                      portName = "VSDServicePort",
                      targetNamespace = "http://ws.gematik.de/conn/vsds/VSDService/v5.2",
                      wsdlLocation = "classpath:/wsdl/VSDService.wsdl",
                      endpointInterface = "de.gematik.ws.conn.vsds.vsdservice.v5_2.VSDServicePortType")

public class VSDServicePortImpl implements VSDServicePortType {


    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(VSDServicePortImpl.class.getName());

    @ConfigProperty(name = "popp.client-url", defaultValue = "http://localhost:8081")
    String poppClientUrl;

    @Override
    public ReadVSDResponse readVSD(ReadVSD parameter) throws FaultMessage {
        LOG.info("Executing operation readVSD");
        ReadVSDResponse _return = new ReadVSDResponse();

        // Do GET call to PoPP client to trigger PoPP Token dance
        // https://github.com/gematik/popp-sample-code/blob/main/popp-client/src/main/java/de/gematik/refpopp/popp_client/controller/CardRestController.java
        URI uri = URI.create(poppClientUrl + "/token/contact-connector?clientsessionid=" + parameter.getEhcHandle());
        try {
            java.net.HttpURLConnection conn = (java.net.HttpURLConnection) uri.toURL().openConnection();
            conn.setRequestMethod("GET");
            conn.setConnectTimeout(30000);
            conn.setReadTimeout(30000);
            int responseCode = conn.getResponseCode();
            LOG.info("GET " + uri + " response code: " + responseCode);
            java.io.InputStream is = (responseCode >= 200 && responseCode < 300) ? conn.getInputStream() : conn.getErrorStream();
            java.util.Scanner scanner = new java.util.Scanner(is).useDelimiter("\\A");
            String poppToken = scanner.hasNext() ? scanner.next() : "";
            LOG.info("Response body: " + poppToken);
            scanner.close();
            is.close();
            _return.setPruefungsnachweis(poppToken.getBytes());
        } catch (Exception e) {
            LOG.severe("GET request to " + uri + " failed: " + e.getMessage());
        }

        return _return;
    }
}
