package de.gematik.ws.conn.vsds.vsdservice.v5_2;

import static org.jboss.resteasy.reactive.RestResponse.StatusCode.OK;

import de.gematik.ws.conn.vsds.vsdservice.v5.ReadVSD;
import de.gematik.ws.conn.vsds.vsdservice.v5.ReadVSDResponse;
import de.servicehealth.popp.session.Store;
import io.vertx.core.json.JsonObject;
import io.vertx.mutiny.core.Vertx;
import io.vertx.mutiny.ext.web.client.WebClient;
import jakarta.annotation.PostConstruct;
import jakarta.inject.Inject;
import jakarta.jws.WebService;
import java.net.URI;
import java.time.Duration;
import java.util.logging.Logger;
import org.eclipse.microprofile.config.inject.ConfigProperty;

/**
 * This class was generated by Apache CXF 4.1.4 2026-02-02T22:57:04.219+01:00 Generated source
 * version: 4.1.4
 */
@WebService(
    serviceName = "VSDService",
    portName = "VSDServicePort",
    targetNamespace = "http://ws.gematik.de/conn/vsds/VSDService/v5.2",
    wsdlLocation = "classpath:/wsdl/VSDService.wsdl",
    endpointInterface = "de.gematik.ws.conn.vsds.vsdservice.v5_2.VSDServicePortType")
public class VSDServicePortImpl implements VSDServicePortType {

  private static final Logger LOG = Logger.getLogger(VSDServicePortImpl.class.getName());

  @ConfigProperty(name = "popp.client-url", defaultValue = "http://localhost:8081")
  String poppClientUrl;

  @Inject Vertx vertx;

  @Inject Store store;

  WebClient webClient;

  @PostConstruct
  private void init() {
    this.webClient = WebClient.create(vertx);
  }

  @Override
  public ReadVSDResponse readVSD(ReadVSD parameter) throws FaultMessage {
    LOG.fine("Executing operation readVSD");
    ReadVSDResponse _return = new ReadVSDResponse();

    var entry = store.findEntry(parameter.getEhcHandle()).orElseThrow();
    var certCN = entry.getTlsCertCN().substring(0, 20);

    // Do GET call to PoPP client to trigger PoPP Token dance
    // https://github.com/gematik/popp-sample-code/blob/main/popp-client/src/main/java/de/gematik/refpopp/popp_client/controller/CardRestController.java
    URI uri = URI.create(poppClientUrl + "/token");

    JsonObject body =
        new JsonObject()
            .put("communicationType", "contact-connector")
            .put("cardId", certCN)
            .put("clientSessionId", parameter.getEhcHandle());

    try {
      var response =
          webClient
              .postAbs(uri.toString())
              .putHeader("Accept", "application/json")
              .sendJson(body)
              .await()
              .atMost(Duration.ofSeconds(10));

      int responseCode = response.statusCode();

      if (responseCode != OK) {
        LOG.severe("POST request to " + uri + " returned non 200 status: \n " + response.body());
        throw new FaultMessage("Fetching PoPP token has failed.");
      }

      String poppToken = response.bodyAsJsonObject().getString("token");
      _return.setPruefungsnachweis(("popp-token: " + poppToken).getBytes());
    } catch (Exception e) {
      LOG.severe("POST request to " + uri + " failed: " + e.getMessage());
    }

    return _return;
  }
}
